export async function handleHelp(): Promise<{ text: string }> {
  return {
    text: [
      "Tower — Your Morning Copilot",
      "",
      "Briefings:",
      "  gm — morning briefing",
      "  gn — night outlook",
      "  CYTZ — decode airport weather",
      "  taf CYTZ — forecast",
      "  brief CYTZ KBUF — route weather",
      "  radar — radar image",
      "  gfa — forecast chart",
      "",
      "Flying:",
      "  winds CYTZ — crosswind breakdown",
      "  flew 1.2 dual — log flight time",
      "  hours — your totals",
      "  currency — am I current?",
      "",
      "Study:",
      "  quiz — METAR decode quiz",
      "  scenario — go/no-go trainer",
      "  explain — break down last weather",
      "",
      "Settings:",
      "  home CYTZ — set home airport",
      "  minimums 1000 3 — ceiling / vis",
      "  wake 0600 — briefing time",
      "  aircraft C172 — your plane",
      "  priority: your task — daily focus",
      "  status — view settings",
    ].join("\n"),
  };
}
